# Generated by Django 5.0.4 on 2024-04-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_test_accountant_labtechnician_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='date',
        ),
        migrations.RemoveField(
            model_name='test',
            name='time',
        ),
        migrations.AddField(
            model_name='test',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
