# Generated by Django 5.0.4 on 2024-04-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_session_testresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='testResults',
        ),
    ]
