# Generated by Django 5.0.4 on 2024-04-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_session_labtechnician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='totalPayment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
