# Generated by Django 5.0.4 on 2024-04-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_test_date_remove_test_time_test_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='test',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='patients.test'),
        ),
    ]
