# Generated by Django 5.0.4 on 2024-04-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_test_result_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='testResults',
            field=models.ManyToManyField(blank=True, related_name='ts', through='patients.TestResult', to='patients.test'),
        ),
    ]
